### PR TITLE
Scalar `UUID`

### PR DESCRIPTION
**Pull request by thegrymek**
Added new scalar that validates and returns python object UUID.
Returns string value.

### CODE REVIEW

**Comment by zer0tonin** [comment]
Isn't this already covered by `GUID`?

**Comment by thegrymek** [comment]
I don't know is a correct way. 

This scalar returns `UUID` object that we have to handle in application. Similar behaviour like `datetime`. I don't know that having `UUID` as object in app will be handy and comfortable.

**Comment by abusi** [comment]
This implementation is similar to the one from GUID but, instead, it uses python UUID objects.
GUID and UUID (https://stackoverflow.com/questions/246930/is-there-any-difference-between-a-guid-and-a-uuid) To sum it up. GUID is a Microsoft term, old MS COM GUID are UUID3, modern MS GUID could be RFC4122 or UUID Variant 4. 
So it's not that bad to have the 2 think separated here. Someone that wants GUID will have a str inside its resolver, someone wanting UUID will have a UUID python object and be able to manipulate it as he wants. 
@zer0tonin Do I make sense? Sometimes I not really sure :p If you approve this, I'll make a release with it.

**Comment by zer0tonin** [comment]
@abusi ok then, if this has a different use case than guid let's release it

**Pull request merged**
